# Generated by Django 4.2.3 on 2023-07-06 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('deadline', models.DateField(verbose_name='Крайний срок')),
                ('priority', models.CharField(choices=[('low', 'Малый'), ('medium', 'Средний'), ('high', 'Высокий')], max_length=20, verbose_name='Приоритет')),
                ('status', models.CharField(choices=[('not_completed', 'Не выполнено'), ('completed', 'Выполнено')], default='not_completed', max_length=20, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Задача',
                'verbose_name_plural': 'Задачи',
                'ordering': ['-created_date', 'title'],
            },
        ),
    ]
